In [18]:
import random
import pandas as pd
from tqdm.notebook import tqdm

In [ ]:
dir(random)

In [10]:
ex_df = pd.DataFrame(
    dict(
        values=[random.randint(1, 1000) for _ in range(100)],
        group1=[random.randint(1, 100) for _ in range(25)] * 4,
        group2=[random.randint(1, 100) for _ in range(4)] * 25
    )
)
print(ex_df)

    values  group1  group2
0      213      30      53
1      916      51      73
2      245      86      90
3      626       7      36
4      660      55      53
..     ...     ...     ...
95     914      90      36
96     140      98      53
97     931      15      73
98     130      47      90
99     147      55      36

[100 rows x 3 columns]

In [19]:
squared_df_list = []
for group1, df in tqdm(ex_df.groupby('group1')):
    print(f'Group {group1}:')
    squared_values = df['values'] ** 2
    display (df)
    df['squared_values'] = squared_values
    squared_df_list.append(df)
    [display (df) for df in squared_df_list]
    time.sleep(2)
pd.concat(squared_df_list)

Group 7:
3     391876
7     853776
28    498436
32    242064
53     77841
57     15625
78    291600
82    313600
Name: values, dtype: int64

    values  group1  group2
3      626       7      36
7      924       7      36
28     706       7      53
32     492       7      53
53     279       7      73
57     125       7      73
78     540       7      90
82     560       7      90

    values  group1  group2  squared_values
3      626       7      36          391876
7      924       7      36          853776
28     706       7      53          498436
32     492       7      53          242064
53     279       7      73           77841
57     125       7      73           15625
78     540       7      90          291600
82     560       7      90          313600

NameError: name 'time' is not defined

In [4]:
# For two different data downloads: NEON data & EMIT data
import os
from datetime import datetime

# --- Function to explore multiple data folders ---
def data_download_tracker(absolute_soap_path, folder_names, extension):
    """
    Explores 'SOAP' directory to confirm data downloaded into correct folders and finds files with a specific extension within those folders and their subdirectories.

    Args:
        absolute_soap_path (str): The absolute path to the root of your project.
        folder_names (list): A list of names of the subfolders within 'SOAP' to explore (e.g., ["EMIT", "NEON"]).
        extension (str): The file extension to search for (".nc", ".shp", ".CHM", ".H5").

    Returns:
        dict: A dictionary where keys are the folder names (e.g., "EMIT", "NEON")
              and values are lists of absolute paths to the found files within that folder.
    """
    all_found_files = {} # To store results for each folder
    
    if not os.path.isdir(absolute_soap_path):
        print(f"Error: The 'SOAP' directory does not exist at: {soap_directory}")
        return all_found_files

    print(f"\n--- Starting exploration within the SOAP directory: {absolute_soap_path} ---")

    for folder_name in folder_names:
        current_data_folder = os.path.join(absolute_soap_path, folder_name)
        if not os.path.isdir(current_data_folder):
            print(f"Warning: Folder '{folder_name}' does not exist at: {current_data_folder}")
            all_found_files[folder_name] = [] # Record an empty list for this folder
            continue
            
        print(f"\n--- Searching for '{extension}' files in: {current_data_folder} ---")
        
        found_files_in_current_folder = []
        for root, _, files in os.walk(current_data_folder):
            for file in files:
                if file.lower().endswith(extension.lower()):
                    full_path = os.path.join(root, file)
                    found_files_in_current_folder.append(full_path)
                    print(f"Found: {full_path}")
                    
        if found_files_in_current_folder:
            print(f"Found {len(found_files_in_current_folder)} '{extension}' files in '{folder_name}'.")
        else:
            print(f"No '{extension}' files found in '{folder_name}'.")

        all_found_files[folder_name] = found_files_in_current_folder

    return all_found_files


# --- Main execution block ---
if __name__ == "__main__":
    # Define the absolute path to the SOAP directory
    soap_absolute_path = r"C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP"

    folder_names = ["EMIT", "NEON"] # Use a list for folder names
    file_extension_to_find = ".nc" # The specific extension you want to find
    

    # Call the combined function
    print("\n--- Starting Data Download Tracker ---")
    found_nc_files_by_folder = data_download_tracker(
        soap_absolute_path,
        folder_names,
        file_extension_to_find
    )

    print("\n--- Summary of Found Files ---")
    for folder, files in found_nc_files_by_folder.items():
        if files:
            print(f"In '{folder}': {len(files)} '{file_extension_to_find}' files found.")
            # For brevity, not printing all paths again here, but you could:
            # for f in files:
            #     print(f"  - {f}")
        else:
            print(f"In '{folder}': No '{file_extension_to_find}' files found.")

--- Starting Data Download Tracker ---

--- Starting exploration within the SOAP directory: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP ---

--- Searching for '.nc' files in: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT ---
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Arefl\EMIT_L2A_MASK_001_20230731T205320_2321214_004.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Arefl\EMIT_L2A_RFLUNCERT_001_20230731T205320_2321214_004.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Arefl\EMIT_L2A_RFL_001_20230731T205320_2321214_004.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Arefl\EMIT_L2A_RFL_001_20230731T205320_2321214_004_SOAP.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Bmineral\EMIT_L2B_MINUNCERT_001_20230731T205320_2321214_004.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L2Bmineral\EMIT_L2B_MIN_001_20230731T205320_2321214_004.nc
Found: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\EMIT\L3mineral\EMIT_L3_ASA_001.nc
Found 7 '.nc' files in 'EMIT'.

--- Searching for '.nc' files in: C:\Users\stem2\Documents\Capstone\AOP-EMIT\data\SOAP\NEON ---
No '.nc' files found in 'NEON'.

--- Summary of Found Files ---
In 'EMIT': 7 '.nc' files found.
In 'NEON': No '.nc' files found.