# Functions & Loops Practice from June 24, 2025 class

In [25]:
import random
import time

import pandas as pd
from tqdm.notebook import tqdm

In [3]:
#check fxns in random module; generally ignore things w/ underscores in front b/c they're used internally
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_ONE',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_accumulate',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_floor',
 '_index',
 '_inst',
 '_isfinite',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_repeat',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randbytes',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [4]:
#get info abt randint fxn
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.

In [13]:
for i in range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [14]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [12]:
#construct example DataFrame
ex_df = pd.DataFrame(
    #with this dict() we don't have to put key names in quotes
    dict(
        values=[random.randint(1, 1000)
                #produces a generator that starts at 0 and counts up to 99
                # this lets us run the loop a certain number of times
                for i in range(100)],
        group1=[random.randint(1, 100) for i in range (25)] * 4,
        #pick 4 random integers btw 1 and 100 and repeat thos 4 numbers over and over 25 times
        group2=[random.randint(1, 100) for i in range (4)] * 25)
    
)
ex_df

    values  group1  group2
0      843      79      53
1      183      19     100
2      699      19      34
3      120      10      63
4       37      40      53
..     ...     ...     ...
95     339      71      63
96     420      86      53
97     919      10     100
98     352      89      34
99     850      10      63

[100 rows x 3 columns]

In [18]:
#loop through dataframe by group
for group2, df in ex_df.groupby('group2'):
    print(group2)
    display(df)

print(group2)

34

    values  group1  group2
2      699      19      34
6      606      93      34
10     891      42      34
14     558      87      34
18     253      63      34
22     625      10      34
26     265      19      34
30     494      66      34
34     928      89      34
38     109      81      34
42     956      82      34
46     661      86      34
50     321      79      34
54     619      40      34
58     408      61      34
62     959      26      34
66     872      47      34
70      22      71      34
74     789      10      34
78     300      10      34
82     656      17      34
86     855      91      34
90     242      87      34
94     717      18      34
98     352      89      34

53

    values  group1  group2
0      843      79      53
4       37      40      53
8      243      61      53
12     188      26      53
16     656      47      53
20     898      71      53
24      10      10      53
28     823      10      53
32     313      17      53
36     556      91      53
40     850      87      53
44     154      18      53
48     910      89      53
52     818      19      53
56     732      93      53
60     386      42      53
64     797      87      53
68     825      63      53
72     236      10      53
76     842      19      53
80     892      66      53
84     734      89      53
88     119      81      53
92      92      82      53
96     420      86      53

63

    values  group1  group2
3      120      10      63
7      409      17      63
11      95      91      63
15     130      87      63
19     641      18      63
23       2      89      63
27     452      19      63
31     534      93      63
35     153      42      63
39      80      87      63
43      47      63      63
47     286      10      63
51     203      19      63
55     993      66      63
59     215      89      63
63     351      81      63
67     698      82      63
71     597      86      63
75     149      79      63
79     601      40      63
83     350      61      63
87     852      26      63
91     357      47      63
95     339      71      63
99     850      10      63

100

    values  group1  group2
1      183      19     100
5      804      66     100
9      747      89     100
13     626      81     100
17     676      82     100
21     172      86     100
25     276      79     100
29     698      40     100
33     373      61     100
37     455      26     100
41     271      47     100
45     391      71     100
49     192      10     100
53     145      10     100
57     270      17     100
61     266      91     100
65     175      87     100
69     708      18     100
73     708      89     100
77     128      19     100
81     607      93     100
85     754      42     100
89     839      87     100
93     455      63     100
97     919      10     100

100

In [26]:
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname']

In [30]:
#set up accumulator list
squared_df_list = []
for group1, df in tqdm(ex_df.groupby('group1')):
    print(f'Group {group1}:')
    squared_values = (
        #sauare dataframe values column
        df['values'] ** 2)
    #add back to df in new column
    df['squared_values'] = squared_values
    #instead of the two lines above, it could just be 
    # df['squared_values']=df['values'] ** 2
    #append new df to list
    squared_df_list.append(df)

#glue the 25 separate lists into one df
pd.concat(squared_df_list)

  0%|          | 0/20 [00:00<?, ?it/s]

Group 10:
Group 17:
Group 18:
Group 19:
Group 26:
Group 40:
Group 42:
Group 47:
Group 61:
Group 63:
Group 66:
Group 71:
Group 79:
Group 81:
Group 82:
Group 86:
Group 87:
Group 89:
Group 91:
Group 93:

    values  group1  group2  squared_values
3      120      10      63           14400
22     625      10      34          390625
24      10      10      53             100
28     823      10      53          677329
47     286      10      63           81796
..     ...     ...     ...             ...
86     855      91      34          731025
6      606      93      34          367236
31     534      93      63          285156
56     732      93      53          535824
81     607      93     100          368449

[100 rows x 4 columns]

In [32]:
#looping w/ iterrows method

#this is a generator which means we can loop through it
ex_df.iterrows()

#this should give us the index of each row and the row contents as a series for each row
for i, row in ex_df.iterrows():
    print (i)
    print (row)

0
values    843
group1     79
group2     53
Name: 0, dtype: int64
1
values    183
group1     19
group2    100
Name: 1, dtype: int64
2
values    699
group1     19
group2     34
Name: 2, dtype: int64
3
values    120
group1     10
group2     63
Name: 3, dtype: int64
4
values    37
group1    40
group2    53
Name: 4, dtype: int64
5
values    804
group1     66
group2    100
Name: 5, dtype: int64
6
values    606
group1     93
group2     34
Name: 6, dtype: int64
7
values    409
group1     17
group2     63
Name: 7, dtype: int64
8
values    243
group1     61
group2     53
Name: 8, dtype: int64
9
values    747
group1     89
group2    100
Name: 9, dtype: int64
10
values    891
group1     42
group2     34
Name: 10, dtype: int64
11
values    95
group1    91
group2    63
Name: 11, dtype: int64
12
values    188
group1     26
group2     53
Name: 12, dtype: int64
13
values    626
group1     81
group2    100
Name: 13, dtype: int64
14
values    558
group1     87
group2     34
Name: 14, dtype: int64
15
values    130
group1     87
group2     63
Name: 15, dtype: int64
16
values    656
group1     47
group2     53
Name: 16, dtype: int64
17
values    676
group1     82
group2    100
Name: 17, dtype: int64
18
values    253
group1     63
group2     34
Name: 18, dtype: int64
19
values    641
group1     18
group2     63
Name: 19, dtype: int64
20
values    898
group1     71
group2     53
Name: 20, dtype: int64
21
values    172
group1     86
group2    100
Name: 21, dtype: int64
22
values    625
group1     10
group2     34
Name: 22, dtype: int64
23
values     2
group1    89
group2    63
Name: 23, dtype: int64
24
values    10
group1    10
group2    53
Name: 24, dtype: int64
25
values    276
group1     79
group2    100
Name: 25, dtype: int64
26
values    265
group1     19
group2     34
Name: 26, dtype: int64
27
values    452
group1     19
group2     63
Name: 27, dtype: int64
28
values    823
group1     10
group2     53
Name: 28, dtype: int64
29
values    698
group1     40
group2    100
Name: 29, dtype: int64
30
values    494
group1     66
group2     34
Name: 30, dtype: int64
31
values    534
group1     93
group2     63
Name: 31, dtype: int64
32
values    313
group1     17
group2     53
Name: 32, dtype: int64
33
values    373
group1     61
group2    100
Name: 33, dtype: int64
34
values    928
group1     89
group2     34
Name: 34, dtype: int64
35
values    153
group1     42
group2     63
Name: 35, dtype: int64
36
values    556
group1     91
group2     53
Name: 36, dtype: int64
37
values    455
group1     26
group2    100
Name: 37, dtype: int64
38
values    109
group1     81
group2     34
Name: 38, dtype: int64
39
values    80
group1    87
group2    63
Name: 39, dtype: int64
40
values    850
group1     87
group2     53
Name: 40, dtype: int64
41
values    271
group1     47
group2    100
Name: 41, dtype: int64
42
values    956
group1     82
group2     34
Name: 42, dtype: int64
43
values    47
group1    63
group2    63
Name: 43, dtype: int64
44
values    154
group1     18
group2     53
Name: 44, dtype: int64
45
values    391
group1     71
group2    100
Name: 45, dtype: int64
46
values    661
group1     86
group2     34
Name: 46, dtype: int64
47
values    286
group1     10
group2     63
Name: 47, dtype: int64
48
values    910
group1     89
group2     53
Name: 48, dtype: int64
49
values    192
group1     10
group2    100
Name: 49, dtype: int64
50
values    321
group1     79
group2     34
Name: 50, dtype: int64
51
values    203
group1     19
group2     63
Name: 51, dtype: int64
52
values    818
group1     19
group2     53
Name: 52, dtype: int64
53
values    145
group1     10
group2    100
Name: 53, dtype: int64
54
values    619
group1     40
group2     34
Name: 54, dtype: int64
55
values    993
group1     66
group2     63
Name: 55, dtype: int64
56
values    732
group1     93
group2     53
Name: 56, dtype: int64
57
values    270
group1     17
group2    100
Name: 57, dtype: int64
58
values    408
group1     61
group2     34
Name: 58, dtype: int64
59
values    215
group1     89
group2     63
Name: 59, dtype: int64
60
values    386
group1     42
group2     53
Name: 60, dtype: int64
61
values    266
group1     91
group2    100
Name: 61, dtype: int64
62
values    959
group1     26
group2     34
Name: 62, dtype: int64
63
values    351
group1     81
group2     63
Name: 63, dtype: int64
64
values    797
group1     87
group2     53
Name: 64, dtype: int64
65
values    175
group1     87
group2    100
Name: 65, dtype: int64
66
values    872
group1     47
group2     34
Name: 66, dtype: int64
67
values    698
group1     82
group2     63
Name: 67, dtype: int64
68
values    825
group1     63
group2     53
Name: 68, dtype: int64
69
values    708
group1     18
group2    100
Name: 69, dtype: int64
70
values    22
group1    71
group2    34
Name: 70, dtype: int64
71
values    597
group1     86
group2     63
Name: 71, dtype: int64
72
values    236
group1     10
group2     53
Name: 72, dtype: int64
73
values    708
group1     89
group2    100
Name: 73, dtype: int64
74
values    789
group1     10
group2     34
Name: 74, dtype: int64
75
values    149
group1     79
group2     63
Name: 75, dtype: int64
76
values    842
group1     19
group2     53
Name: 76, dtype: int64
77
values    128
group1     19
group2    100
Name: 77, dtype: int64
78
values    300
group1     10
group2     34
Name: 78, dtype: int64
79
values    601
group1     40
group2     63
Name: 79, dtype: int64
80
values    892
group1     66
group2     53
Name: 80, dtype: int64
81
values    607
group1     93
group2    100
Name: 81, dtype: int64
82
values    656
group1     17
group2     34
Name: 82, dtype: int64
83
values    350
group1     61
group2     63
Name: 83, dtype: int64
84
values    734
group1     89
group2     53
Name: 84, dtype: int64
85
values    754
group1     42
group2    100
Name: 85, dtype: int64
86
values    855
group1     91
group2     34
Name: 86, dtype: int64
87
values    852
group1     26
group2     63
Name: 87, dtype: int64
88
values    119
group1     81
group2     53
Name: 88, dtype: int64
89
values    839
group1     87
group2    100
Name: 89, dtype: int64
90
values    242
group1     87
group2     34
Name: 90, dtype: int64
91
values    357
group1     47
group2     63
Name: 91, dtype: int64
92
values    92
group1    82
group2    53
Name: 92, dtype: int64
93
values    455
group1     63
group2    100
Name: 93, dtype: int64
94
values    717
group1     18
group2     34
Name: 94, dtype: int64
95
values    339
group1     71
group2     63
Name: 95, dtype: int64
96
values    420
group1     86
group2     53
Name: 96, dtype: int64
97
values    919
group1     10
group2    100
Name: 97, dtype: int64
98
values    352
group1     89
group2     34
Name: 98, dtype: int64
99
values    850
group1     10
group2     63
Name: 99, dtype: int64

In [33]:
#this should give us the index of each row and the row contents as a series for each row
for i, row in ex_df.iterrows():
    print (f'Row {i}:')
    print (row)
    #add a blank line in btw each
    print('\n')

Row 0:
values    843
group1     79
group2     53
Name: 0, dtype: int64


Row 1:
values    183
group1     19
group2    100
Name: 1, dtype: int64


Row 2:
values    699
group1     19
group2     34
Name: 2, dtype: int64


Row 3:
values    120
group1     10
group2     63
Name: 3, dtype: int64


Row 4:
values    37
group1    40
group2    53
Name: 4, dtype: int64


Row 5:
values    804
group1     66
group2    100
Name: 5, dtype: int64


Row 6:
values    606
group1     93
group2     34
Name: 6, dtype: int64


Row 7:
values    409
group1     17
group2     63
Name: 7, dtype: int64


Row 8:
values    243
group1     61
group2     53
Name: 8, dtype: int64


Row 9:
values    747
group1     89
group2    100
Name: 9, dtype: int64


Row 10:
values    891
group1     42
group2     34
Name: 10, dtype: int64


Row 11:
values    95
group1    91
group2    63
Name: 11, dtype: int64


Row 12:
values    188
group1     26
group2     53
Name: 12, dtype: int64


Row 13:
values    626
group1     81
group2    100
Name: 13, dtype: int64


Row 14:
values    558
group1     87
group2     34
Name: 14, dtype: int64


Row 15:
values    130
group1     87
group2     63
Name: 15, dtype: int64


Row 16:
values    656
group1     47
group2     53
Name: 16, dtype: int64


Row 17:
values    676
group1     82
group2    100
Name: 17, dtype: int64


Row 18:
values    253
group1     63
group2     34
Name: 18, dtype: int64


Row 19:
values    641
group1     18
group2     63
Name: 19, dtype: int64


Row 20:
values    898
group1     71
group2     53
Name: 20, dtype: int64


Row 21:
values    172
group1     86
group2    100
Name: 21, dtype: int64


Row 22:
values    625
group1     10
group2     34
Name: 22, dtype: int64


Row 23:
values     2
group1    89
group2    63
Name: 23, dtype: int64


Row 24:
values    10
group1    10
group2    53
Name: 24, dtype: int64


Row 25:
values    276
group1     79
group2    100
Name: 25, dtype: int64


Row 26:
values    265
group1     19
group2     34
Name: 26, dtype: int64


Row 27:
values    452
group1     19
group2     63
Name: 27, dtype: int64


Row 28:
values    823
group1     10
group2     53
Name: 28, dtype: int64


Row 29:
values    698
group1     40
group2    100
Name: 29, dtype: int64


Row 30:
values    494
group1     66
group2     34
Name: 30, dtype: int64


Row 31:
values    534
group1     93
group2     63
Name: 31, dtype: int64


Row 32:
values    313
group1     17
group2     53
Name: 32, dtype: int64


Row 33:
values    373
group1     61
group2    100
Name: 33, dtype: int64


Row 34:
values    928
group1     89
group2     34
Name: 34, dtype: int64


Row 35:
values    153
group1     42
group2     63
Name: 35, dtype: int64


Row 36:
values    556
group1     91
group2     53
Name: 36, dtype: int64


Row 37:
values    455
group1     26
group2    100
Name: 37, dtype: int64


Row 38:
values    109
group1     81
group2     34
Name: 38, dtype: int64


Row 39:
values    80
group1    87
group2    63
Name: 39, dtype: int64


Row 40:
values    850
group1     87
group2     53
Name: 40, dtype: int64


Row 41:
values    271
group1     47
group2    100
Name: 41, dtype: int64


Row 42:
values    956
group1     82
group2     34
Name: 42, dtype: int64


Row 43:
values    47
group1    63
group2    63
Name: 43, dtype: int64


Row 44:
values    154
group1     18
group2     53
Name: 44, dtype: int64


Row 45:
values    391
group1     71
group2    100
Name: 45, dtype: int64


Row 46:
values    661
group1     86
group2     34
Name: 46, dtype: int64


Row 47:
values    286
group1     10
group2     63
Name: 47, dtype: int64


Row 48:
values    910
group1     89
group2     53
Name: 48, dtype: int64


Row 49:
values    192
group1     10
group2    100
Name: 49, dtype: int64


Row 50:
values    321
group1     79
group2     34
Name: 50, dtype: int64


Row 51:
values    203
group1     19
group2     63
Name: 51, dtype: int64


Row 52:
values    818
group1     19
group2     53
Name: 52, dtype: int64


Row 53:
values    145
group1     10
group2    100
Name: 53, dtype: int64


Row 54:
values    619
group1     40
group2     34
Name: 54, dtype: int64


Row 55:
values    993
group1     66
group2     63
Name: 55, dtype: int64


Row 56:
values    732
group1     93
group2     53
Name: 56, dtype: int64


Row 57:
values    270
group1     17
group2    100
Name: 57, dtype: int64


Row 58:
values    408
group1     61
group2     34
Name: 58, dtype: int64


Row 59:
values    215
group1     89
group2     63
Name: 59, dtype: int64


Row 60:
values    386
group1     42
group2     53
Name: 60, dtype: int64


Row 61:
values    266
group1     91
group2    100
Name: 61, dtype: int64


Row 62:
values    959
group1     26
group2     34
Name: 62, dtype: int64


Row 63:
values    351
group1     81
group2     63
Name: 63, dtype: int64


Row 64:
values    797
group1     87
group2     53
Name: 64, dtype: int64


Row 65:
values    175
group1     87
group2    100
Name: 65, dtype: int64


Row 66:
values    872
group1     47
group2     34
Name: 66, dtype: int64


Row 67:
values    698
group1     82
group2     63
Name: 67, dtype: int64


Row 68:
values    825
group1     63
group2     53
Name: 68, dtype: int64


Row 69:
values    708
group1     18
group2    100
Name: 69, dtype: int64


Row 70:
values    22
group1    71
group2    34
Name: 70, dtype: int64


Row 71:
values    597
group1     86
group2     63
Name: 71, dtype: int64


Row 72:
values    236
group1     10
group2     53
Name: 72, dtype: int64


Row 73:
values    708
group1     89
group2    100
Name: 73, dtype: int64


Row 74:
values    789
group1     10
group2     34
Name: 74, dtype: int64


Row 75:
values    149
group1     79
group2     63
Name: 75, dtype: int64


Row 76:
values    842
group1     19
group2     53
Name: 76, dtype: int64


Row 77:
values    128
group1     19
group2    100
Name: 77, dtype: int64


Row 78:
values    300
group1     10
group2     34
Name: 78, dtype: int64


Row 79:
values    601
group1     40
group2     63
Name: 79, dtype: int64


Row 80:
values    892
group1     66
group2     53
Name: 80, dtype: int64


Row 81:
values    607
group1     93
group2    100
Name: 81, dtype: int64


Row 82:
values    656
group1     17
group2     34
Name: 82, dtype: int64


Row 83:
values    350
group1     61
group2     63
Name: 83, dtype: int64


Row 84:
values    734
group1     89
group2     53
Name: 84, dtype: int64


Row 85:
values    754
group1     42
group2    100
Name: 85, dtype: int64


Row 86:
values    855
group1     91
group2     34
Name: 86, dtype: int64


Row 87:
values    852
group1     26
group2     63
Name: 87, dtype: int64


Row 88:
values    119
group1     81
group2     53
Name: 88, dtype: int64


Row 89:
values    839
group1     87
group2    100
Name: 89, dtype: int64


Row 90:
values    242
group1     87
group2     34
Name: 90, dtype: int64


Row 91:
values    357
group1     47
group2     63
Name: 91, dtype: int64


Row 92:
values    92
group1    82
group2    53
Name: 92, dtype: int64


Row 93:
values    455
group1     63
group2    100
Name: 93, dtype: int64


Row 94:
values    717
group1     18
group2     34
Name: 94, dtype: int64


Row 95:
values    339
group1     71
group2     63
Name: 95, dtype: int64


Row 96:
values    420
group1     86
group2     53
Name: 96, dtype: int64


Row 97:
values    919
group1     10
group2    100
Name: 97, dtype: int64


Row 98:
values    352
group1     89
group2     34
Name: 98, dtype: int64


Row 99:
values    850
group1     10
group2     63
Name: 99, dtype: int64

In [41]:
#this should give us the index of each row and the row contents as a series for each row
#formatting prints in this way can help us debug to see different printouts clearly
for i, row in ex_df.iterrows():
    print (f'Row {i}:')
    #\t indents
    print (f"\tValue: {row['values']}")
    print (f"\tGroup1: {row['group1']}")
    print (f"\tGroup2: {row['group2']}")
    print('\n')

Row 0:
	Value: 843
	Group1: 79
	Group2: 53


Row 1:
	Value: 183
	Group1: 19
	Group2: 100


Row 2:
	Value: 699
	Group1: 19
	Group2: 34


Row 3:
	Value: 120
	Group1: 10
	Group2: 63


Row 4:
	Value: 37
	Group1: 40
	Group2: 53


Row 5:
	Value: 804
	Group1: 66
	Group2: 100


Row 6:
	Value: 606
	Group1: 93
	Group2: 34


Row 7:
	Value: 409
	Group1: 17
	Group2: 63


Row 8:
	Value: 243
	Group1: 61
	Group2: 53


Row 9:
	Value: 747
	Group1: 89
	Group2: 100


Row 10:
	Value: 891
	Group1: 42
	Group2: 34


Row 11:
	Value: 95
	Group1: 91
	Group2: 63


Row 12:
	Value: 188
	Group1: 26
	Group2: 53


Row 13:
	Value: 626
	Group1: 81
	Group2: 100


Row 14:
	Value: 558
	Group1: 87
	Group2: 34


Row 15:
	Value: 130
	Group1: 87
	Group2: 63


Row 16:
	Value: 656
	Group1: 47
	Group2: 53


Row 17:
	Value: 676
	Group1: 82
	Group2: 100


Row 18:
	Value: 253
	Group1: 63
	Group2: 34


Row 19:
	Value: 641
	Group1: 18
	Group2: 63


Row 20:
	Value: 898
	Group1: 71
	Group2: 53


Row 21:
	Value: 172
	Group1: 86
	Group2: 100


Row 22:
	Value: 625
	Group1: 10
	Group2: 34


Row 23:
	Value: 2
	Group1: 89
	Group2: 63


Row 24:
	Value: 10
	Group1: 10
	Group2: 53


Row 25:
	Value: 276
	Group1: 79
	Group2: 100


Row 26:
	Value: 265
	Group1: 19
	Group2: 34


Row 27:
	Value: 452
	Group1: 19
	Group2: 63


Row 28:
	Value: 823
	Group1: 10
	Group2: 53


Row 29:
	Value: 698
	Group1: 40
	Group2: 100


Row 30:
	Value: 494
	Group1: 66
	Group2: 34


Row 31:
	Value: 534
	Group1: 93
	Group2: 63


Row 32:
	Value: 313
	Group1: 17
	Group2: 53


Row 33:
	Value: 373
	Group1: 61
	Group2: 100


Row 34:
	Value: 928
	Group1: 89
	Group2: 34


Row 35:
	Value: 153
	Group1: 42
	Group2: 63


Row 36:
	Value: 556
	Group1: 91
	Group2: 53


Row 37:
	Value: 455
	Group1: 26
	Group2: 100


Row 38:
	Value: 109
	Group1: 81
	Group2: 34


Row 39:
	Value: 80
	Group1: 87
	Group2: 63


Row 40:
	Value: 850
	Group1: 87
	Group2: 53


Row 41:
	Value: 271
	Group1: 47
	Group2: 100


Row 42:
	Value: 956
	Group1: 82
	Group2: 34


Row 43:
	Value: 47
	Group1: 63
	Group2: 63


Row 44:
	Value: 154
	Group1: 18
	Group2: 53


Row 45:
	Value: 391
	Group1: 71
	Group2: 100


Row 46:
	Value: 661
	Group1: 86
	Group2: 34


Row 47:
	Value: 286
	Group1: 10
	Group2: 63


Row 48:
	Value: 910
	Group1: 89
	Group2: 53


Row 49:
	Value: 192
	Group1: 10
	Group2: 100


Row 50:
	Value: 321
	Group1: 79
	Group2: 34


Row 51:
	Value: 203
	Group1: 19
	Group2: 63


Row 52:
	Value: 818
	Group1: 19
	Group2: 53


Row 53:
	Value: 145
	Group1: 10
	Group2: 100


Row 54:
	Value: 619
	Group1: 40
	Group2: 34


Row 55:
	Value: 993
	Group1: 66
	Group2: 63


Row 56:
	Value: 732
	Group1: 93
	Group2: 53


Row 57:
	Value: 270
	Group1: 17
	Group2: 100


Row 58:
	Value: 408
	Group1: 61
	Group2: 34


Row 59:
	Value: 215
	Group1: 89
	Group2: 63


Row 60:
	Value: 386
	Group1: 42
	Group2: 53


Row 61:
	Value: 266
	Group1: 91
	Group2: 100


Row 62:
	Value: 959
	Group1: 26
	Group2: 34


Row 63:
	Value: 351
	Group1: 81
	Group2: 63


Row 64:
	Value: 797
	Group1: 87
	Group2: 53


Row 65:
	Value: 175
	Group1: 87
	Group2: 100


Row 66:
	Value: 872
	Group1: 47
	Group2: 34


Row 67:
	Value: 698
	Group1: 82
	Group2: 63


Row 68:
	Value: 825
	Group1: 63
	Group2: 53


Row 69:
	Value: 708
	Group1: 18
	Group2: 100


Row 70:
	Value: 22
	Group1: 71
	Group2: 34


Row 71:
	Value: 597
	Group1: 86
	Group2: 63


Row 72:
	Value: 236
	Group1: 10
	Group2: 53


Row 73:
	Value: 708
	Group1: 89
	Group2: 100


Row 74:
	Value: 789
	Group1: 10
	Group2: 34


Row 75:
	Value: 149
	Group1: 79
	Group2: 63


Row 76:
	Value: 842
	Group1: 19
	Group2: 53


Row 77:
	Value: 128
	Group1: 19
	Group2: 100


Row 78:
	Value: 300
	Group1: 10
	Group2: 34


Row 79:
	Value: 601
	Group1: 40
	Group2: 63


Row 80:
	Value: 892
	Group1: 66
	Group2: 53


Row 81:
	Value: 607
	Group1: 93
	Group2: 100


Row 82:
	Value: 656
	Group1: 17
	Group2: 34


Row 83:
	Value: 350
	Group1: 61
	Group2: 63


Row 84:
	Value: 734
	Group1: 89
	Group2: 53


Row 85:
	Value: 754
	Group1: 42
	Group2: 100


Row 86:
	Value: 855
	Group1: 91
	Group2: 34


Row 87:
	Value: 852
	Group1: 26
	Group2: 63


Row 88:
	Value: 119
	Group1: 81
	Group2: 53


Row 89:
	Value: 839
	Group1: 87
	Group2: 100


Row 90:
	Value: 242
	Group1: 87
	Group2: 34


Row 91:
	Value: 357
	Group1: 47
	Group2: 63


Row 92:
	Value: 92
	Group1: 82
	Group2: 53


Row 93:
	Value: 455
	Group1: 63
	Group2: 100


Row 94:
	Value: 717
	Group1: 18
	Group2: 34


Row 95:
	Value: 339
	Group1: 71
	Group2: 63


Row 96:
	Value: 420
	Group1: 86
	Group2: 53


Row 97:
	Value: 919
	Group1: 10
	Group2: 100


Row 98:
	Value: 352
	Group1: 89
	Group2: 34


Row 99:
	Value: 850
	Group1: 10
	Group2: 63

In [48]:
#create accumulator list
new_row_list = []

#we can use this to have loop run a few times w/o the break
i = 0

for row_no, row in tqdm(ex_df.iterrows()):
    if i > 5:
        break
    #make a dictionary to add to new_row_list
    new_row = dict(
        values = row['values'],
        grp1_plus_grp2 = row['group1'] + row['group2']
    )
    print(new_row)
    new_row_list.append(new_row)
    #this lets us see some progress of the loop w/o seeing the structure of the whole list
    print(f'Number of rows: {len(new_row_list)}\n')
    i += 1

#we get a list of dictionaries, possibly easier to work w/ list of dictionaries than dictionaries of list
new_row_list

0it [00:00, ?it/s]

{'values': 843, 'grp1_plus_grp2': 132}
Number of rows: 1

{'values': 183, 'grp1_plus_grp2': 119}
Number of rows: 2

{'values': 699, 'grp1_plus_grp2': 53}
Number of rows: 3

{'values': 120, 'grp1_plus_grp2': 73}
Number of rows: 4

{'values': 37, 'grp1_plus_grp2': 93}
Number of rows: 5

{'values': 804, 'grp1_plus_grp2': 166}
Number of rows: 6

[{'values': 843, 'grp1_plus_grp2': 132},
 {'values': 183, 'grp1_plus_grp2': 119},
 {'values': 699, 'grp1_plus_grp2': 53},
 {'values': 120, 'grp1_plus_grp2': 73},
 {'values': 37, 'grp1_plus_grp2': 93},
 {'values': 804, 'grp1_plus_grp2': 166}]

In [49]:
#create accumulator list
new_row_list = []

#we can use this to have loop run a few times w/o the break
i = 0

for row_no, row in tqdm(ex_df.iterrows()):
    if i > 5:
        break
    #make a dictionary to add to new_row_list
    new_row = dict(
        values = row['values'],
        grp1_plus_grp2 = row['group1'] + row['group2']
    )
    print(new_row)
    new_row_list.append(new_row)
    #this lets us see some progress of the loop w/o seeing the structure of the whole list
    print(f'Number of rows: {len(new_row_list)}\n')
    i += 1

pd.DataFrame(new_row_list)

0it [00:00, ?it/s]

{'values': 843, 'grp1_plus_grp2': 132}
Number of rows: 1

{'values': 183, 'grp1_plus_grp2': 119}
Number of rows: 2

{'values': 699, 'grp1_plus_grp2': 53}
Number of rows: 3

{'values': 120, 'grp1_plus_grp2': 73}
Number of rows: 4

{'values': 37, 'grp1_plus_grp2': 93}
Number of rows: 5

{'values': 804, 'grp1_plus_grp2': 166}
Number of rows: 6

   values  grp1_plus_grp2
0     843             132
1     183             119
2     699              53
3     120              73
4      37              93
5     804             166

In [50]:
#create accumulator list
new_row_list = []

for row_no, row in tqdm(ex_df.iterrows()):
    #make a dictionary to add to new_row_list
    new_row = dict(
        values = row['values'],
        grp1_plus_grp2 = row['group1'] + row['group2']
    )
    new_row_list.append(new_row)

pd.DataFrame(new_row_list)

0it [00:00, ?it/s]

    values  grp1_plus_grp2
0      843             132
1      183             119
2      699              53
3      120              73
4       37              93
..     ...             ...
95     339             134
96     420             139
97     919             110
98     352             123
99     850              73

[100 rows x 2 columns]

In [52]:
#create accumulator list
new_row_list = []

#add some conditions on this
for row_no, row in tqdm(ex_df.iterrows()):
    #this just gives values when group1 is less than 15
    #it skips rows that have a group 1 value greater than 15
    if row['group1'] > 15:
        continue
    #make a dictionary to add to new_row_list
    new_row = dict(
        values = row['values'],
        group1 = row['group1'],
        grp1_plus_grp2 = row['group1'] + row['group2']
    )
    new_row_list.append(new_row)

pd.DataFrame(new_row_list)

0it [00:00, ?it/s]

    values  group1  grp1_plus_grp2
0      120      10              73
1      625      10              44
2       10      10              63
3      823      10              63
4      286      10              73
5      192      10             110
6      145      10             110
7      236      10              63
8      789      10              44
9      300      10              44
10     919      10             110
11     850      10              73

In [57]:
#initialize a dictionary as the accumulator w/ rows initialized
df_col_dict = {'values': [], 'grp1_plus_grp2': []}

for row_no, row in tqdm(ex_df.iterrows()):
    df_col_dict['values'].append(row['values'])
    df_col_dict['grp1_plus_grp2'].append(row['group1'] + row['group2'])

pd.DataFrame(df_col_dict)

0it [00:00, ?it/s]

    values  grp1_plus_grp2
0      843             132
1      183             119
2      699              53
3      120              73
4       37              93
..     ...             ...
95     339             134
96     420             139
97     919             110
98     352             123
99     850              73

[100 rows x 2 columns]

In [59]:
#initialize a dictionary as the accumulator w/ rows initialized
df_col_dict = {}

for row_no, row in tqdm(ex_df.iterrows()):
    df_col_dict[row['group2']] = row['values']

df_col_dict

0it [00:00, ?it/s]

{53: 420, 100: 919, 34: 352, 63: 850}

In [62]:
#initialize a dictionary as the accumulator w/ rows initialized
df_col_dict = {}

for row_no, row in tqdm(ex_df.iterrows()):
    if not row['group2'] in df_col_dict:
        df_col_dict[row['group2']] = []
    df_col_dict[row['group2']].append(row['values'])

pd.DataFrame(df_col_dict)

0it [00:00, ?it/s]

    53   100  34   63
0   843  183  699  120
1    37  804  606  409
2   243  747  891   95
3   188  626  558  130
4   656  676  253  641
5   898  172  625    2
6    10  276  265  452
7   823  698  494  534
8   313  373  928  153
9   556  455  109   80
10  850  271  956   47
11  154  391  661  286
12  910  192  321  203
13  818  145  619  993
14  732  270  408  215
15  386  266  959  351
16  797  175  872  698
17  825  708   22  597
18  236  708  789  149
19  842  128  300  601
20  892  607  656  350
21  734  754  855  852
22  119  839  242  357
23   92  455  717  339
24  420  919  352  850